# Generated by Django 4.2.2 on 2023-06-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('FamLink', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('isJoined', models.BooleanField()),
                ('Detail', models.CharField(max_length=200)),
            ],
        ),
    ]
