# Generated by Django 4.2.2 on 2023-06-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_maindb_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterAccountDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('FamLink', models.CharField(max_length=200)),
                ('MemNum', models.IntegerField()),
                ('Date', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='maindb',
            old_name='Date',
            new_name='Datetime',
        ),
    ]
