# Generated by Django 4.2.2 on 2023-06-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_masteraccountdb_rename_date_maindb_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteraccountdb',
            name='Address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masteraccountdb',
            name='Nation',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
