# Generated by Django 4.2.2 on 2023-06-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_masteraccountdb_address_masteraccountdb_nation'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindb',
            name='MasterAccout',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
