# Generated by Django 4.2.2 on 2023-07-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_maindb_masteraccout'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCodeDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VerCode', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=20)),
                ('Remark', models.CharField(max_length=200)),
            ],
        ),
    ]
