# Generated by Django 4.2.2 on 2023-07-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_verificationcodedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindb',
            name='VerCode',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
