# Generated by Django 4.2.3 on 2023-07-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_maindb_vercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteraccountdb',
            name='Remark',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
