# Generated by Django 4.2.2 on 2023-07-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_masteraccountdb_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masteraccountdb',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='masteraccountdb',
            name='Remark',
        ),
    ]
