# Generated by Django 4.2.2 on 2023-07-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_remove_masteraccountdb_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masteraccountdb',
            name='Nation',
        ),
    ]
