# Generated by Django 4.2.2 on 2023-07-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_masteraccountdb_nation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListAccountFamilyDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MasterAccount', models.CharField(max_length=20)),
                ('FamLink', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('JoinedNum', models.IntegerField()),
                ('JoinedAcc', models.CharField(max_length=2000)),
                ('Date', models.CharField(max_length=50)),
            ],
        ),
    ]
