# Generated by Django 4.2.2 on 2023-07-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_listaccountfamilydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActiveNation', models.CharField(max_length=20)),
            ],
        ),
    ]
