# Generated by Django 4.2.2 on 2023-07-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_storeddb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyManamentDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Protocol', models.CharField(max_length=20)),
                ('IP', models.CharField(max_length=50)),
                ('Proxy_User', models.CharField(max_length=50)),
                ('Proxy_PW', models.CharField(max_length=50)),
                ('Nation', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='ListAccountFamilyDB',
        ),
    ]
