# Generated by Django 4.2.2 on 2023-07-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_proxymanamentdb_delete_listaccountfamilydb'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxymanamentdb',
            name='ActivetedDate',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
